window.marketData = {
  STORAGE_KEY: "cuhksz-remarket-state",
  LANGUAGE_KEY: "cuhksz-remarket-language",
  initialListings: [
    {
      id: 1,
      title: "CSC1008 Notes + Past Papers Bundle",
      titleZh: "CSC1008 笔记与历年卷套装",
      category: "Textbooks",
      categoryZh: "教材资料",
      price: 65,
      condition: "Like New",
      conditionZh: "几乎全新",
      seller: "Ada Li",
      rating: 4.9,
      location: "University Library",
      locationZh: "大学图书馆",
      badge: "Best Match",
      badgeZh: "最佳匹配",
      description:
        "Clean and organized course notes with annotated past papers. Ideal for revision week and includes summary sheets.",
      descriptionZh: "整理清晰的课程笔记和带标注的历年试卷，适合复习周使用，并附有总结提纲。",
      tags: ["CSC1008", "Finals", "Bundle"],
      tagsZh: ["CSC1008", "期末复习", "套装"],
      image:
        "https://cuhk.edu.cn/sites/webmaster.prod1.dpsite04.cuhk.edu.cn/files/styles/w500/public/2026-04/%E9%98%BF%E5%8D%A1%E8%B4%9D%E6%8B%89.jpg?itok=4Xxppr_i",
    },
    {
      id: 2,
      title: "iPad Air 5 with Pencil Case",
      titleZh: "iPad Air 5 含笔槽保护套",
      category: "Electronics",
      categoryZh: "电子产品",
      price: 2450,
      condition: "Good",
      conditionZh: "成色良好",
      seller: "Kevin Ma",
      rating: 4.8,
      location: "Shaw Square",
      locationZh: "逸夫广场",
      badge: "Trending",
      badgeZh: "热门商品",
      description:
        "Used for one academic year, fully functional and comes with a charger, sleeve and note-taking app account transfer.",
      descriptionZh: "使用一个学年，功能完好，附带充电器、保护套和记笔记应用账号交接。",
      tags: ["Tablet", "Notes", "Portable"],
      tagsZh: ["平板", "记笔记", "便携"],
      image:
        "https://cuhk.edu.cn/sites/webmaster.prod1.dpsite04.cuhk.edu.cn/files/styles/w500/public/2026-04/%E5%B0%81%E9%9D%A2_1_0.jpg?itok=lIubHR3P",
    },
    {
      id: 3,
      title: "Dorm Desk Lamp and Storage Rack",
      titleZh: "宿舍台灯与收纳架",
      category: "Dorm Essentials",
      categoryZh: "宿舍用品",
      price: 90,
      condition: "Good",
      conditionZh: "成色良好",
      seller: "Mia Chen",
      rating: 4.7,
      location: "Dorm 7 Lobby",
      locationZh: "七号宿舍大堂",
      badge: "Budget Pick",
      badgeZh: "性价比之选",
      description:
        "Compact lamp plus stackable storage rack for dorm desks. Great for move-out season and easy to carry.",
      descriptionZh: "紧凑型台灯搭配可叠放收纳架，适合宿舍桌面，搬宿舍时也方便携带。",
      tags: ["Dorm", "Move-out", "Bundle"],
      tagsZh: ["宿舍", "搬宿舍", "套装"],
      image:
        "https://cuhk.edu.cn/sites/webmaster.prod1.dpsite04.cuhk.edu.cn/files/styles/w500/public/2026-04/image001_5.jpg?itok=JvDwiGVk",
    },
    {
      id: 4,
      title: "Formal Blazer for Presentation Week",
      titleZh: "展示周正式西装外套",
      category: "Fashion",
      categoryZh: "服饰穿搭",
      price: 120,
      condition: "Like New",
      conditionZh: "几乎全新",
      seller: "Jason Wu",
      rating: 4.6,
      location: "Teaching A",
      locationZh: "TA 教学楼",
      badge: "Top Rated",
      badgeZh: "高评分",
      description:
        "Slim-fit navy blazer worn twice for presentations. Clean finish and suitable for interviews or formal events.",
      descriptionZh: "修身海军蓝西装外套，仅在展示时穿过两次，适合面试和正式活动。",
      tags: ["Interview", "Presentation", "Unisex"],
      tagsZh: ["面试", "展示", "中性款"],
      image:
        "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80",
    },
    {
      id: 5,
      title: "Badminton Racket Set x2",
      titleZh: "双人羽毛球拍套装",
      category: "Club & Sports",
      categoryZh: "社团运动",
      price: 180,
      condition: "Fair",
      conditionZh: "正常使用痕迹",
      seller: "Nicole Tang",
      rating: 4.5,
      location: "Sports Hall",
      locationZh: "体育馆",
      badge: "Fast Sale",
      badgeZh: "快速出手",
      description:
        "Two lightweight rackets with shuttlecocks included. Good starter set for casual games and club practice.",
      descriptionZh: "两支轻量球拍并附带羽毛球，适合日常娱乐和社团训练入门。",
      tags: ["Sports", "Set", "Campus Life"],
      tagsZh: ["运动", "套装", "校园生活"],
      image:
        "https://images.unsplash.com/photo-1542144582-1ba00456b5e3?auto=format&fit=crop&w=1200&q=80",
    },
    {
      id: 6,
      title: "Microeconomics Textbook 10th Edition",
      titleZh: "微观经济学教材第十版",
      category: "Textbooks",
      categoryZh: "教材资料",
      price: 88,
      condition: "Good",
      conditionZh: "成色良好",
      seller: "Eric Zhou",
      rating: 4.8,
      location: "TA Building Cafe",
      locationZh: "TA 楼咖啡区",
      badge: "Course Match",
      badgeZh: "课程匹配",
      description:
        "Highlighted only in the first two chapters. Includes chapter summaries and sticky-note definitions for quick review.",
      descriptionZh: "只有前两章有少量划线，附有章节总结和便签定义，适合快速复习。",
      tags: ["ECO", "Textbook", "Annotated"],
      tagsZh: ["ECO", "教材", "有批注"],
      image:
        "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80",
    },
  ],
};
