window.marketData = {
  STORAGE_KEY: "campux-state",
  LANGUAGE_KEY: "campux-language",
  initialListings: [
    {
      id: 2,
      title: "iPad Air 5 with Pencil Case",
      titleZh: "iPad Air 5 含笔槽保护套",
      category: "Electronics",
      categoryZh: "电子产品",
      price: 2450,
      condition: "Visible Signs of Use",
      conditionZh: "明显使用痕迹",
      seller: "Kevin Ma",
      rating: 4.8,
      location: "Teaching A Lobby",
      locationZh: "TA 教学楼大堂",
      badge: "Trending",
      badgeZh: "热门商品",
      description:
        "Used for one academic year, fully functional and comes with a charger, sleeve and note-taking app account transfer.",
      descriptionZh: "使用一个学年，功能完好，附带充电器、保护套和记笔记应用账号交接。",
      tags: ["Tablet", "Notes", "Portable"],
      tagsZh: ["平板", "记笔记", "便携"],
      image: "./photo/iPad Air 5 含笔槽保护套.jpeg",
    },
    {
      id: 3,
      title: "Dorm Desk Lamp and Storage Rack",
      titleZh: "宿舍台灯与收纳架",
      category: "Lifestyle Essentials",
      categoryZh: "生活用品",
      price: 90,
      condition: "Visible Signs of Use",
      conditionZh: "明显使用痕迹",
      seller: "Mia Chen",
      rating: 4.7,
      location: "Dorm 7 Lobby",
      locationZh: "七号宿舍大堂",
      badge: "Budget Pick",
      badgeZh: "性价比之选",
      description:
        "Compact lamp plus stackable storage rack for dorm desks. Great for move-out season and easy to carry.",
      descriptionZh: "紧凑型台灯搭配可叠放收纳架，适合宿舍桌面，搬宿舍时也方便携带。",
      tags: ["Dorm", "Move-out", "Bundle"],
      tagsZh: ["宿舍", "搬宿舍", "套装"],
      image: "./photo/宿舍台灯与收纳架.png",
    },
    {
      id: 4,
      title: "Formal Blazer for Presentation Week",
      titleZh: "展示周正式西装外套",
      category: "Fashion",
      categoryZh: "服饰穿搭",
      price: 120,
      condition: "Brand New",
      conditionZh: "全新",
      seller: "Jason Wu",
      rating: 4.6,
      location: "Teaching A",
      locationZh: "TA 教学楼",
      badge: "Top Rated",
      badgeZh: "高评分",
      description:
        "Slim-fit navy blazer worn twice for presentations. Clean finish and suitable for interviews or formal events.",
      descriptionZh: "修身海军蓝西装外套，仅在展示时穿过两次，适合面试和正式活动。",
      tags: ["Interview", "Presentation", "Unisex"],
      tagsZh: ["面试", "展示", "中性款"],
      image: "./photo/展示周正式西装外套.webp",
    },
    {
      id: 6,
      title: "Microeconomics Textbook",
      titleZh: "微观经济学教材",
      category: "Textbooks",
      categoryZh: "教材资料",
      price: 88,
      condition: "Stained",
      conditionZh: "污损",
      seller: "Eric Zhou",
      rating: 4.8,
      location: "TA Building Cafe",
      locationZh: "TA 楼咖啡区",
      badge: "Course Match",
      badgeZh: "课程匹配",
      description:
        "Highlighted only in the first two chapters. Includes chapter summaries and sticky-note definitions for quick review.",
      descriptionZh: "只有前两章有少量划线，附有章节总结和便签定义，适合快速复习。",
      tags: ["ECO", "Textbook", "Annotated"],
      tagsZh: ["ECO", "教材", "有批注"],
      image: "./photo/微观经济学教材.jpeg",
    },
  ],
  initialWantedPosts: [
    {
      id: 1001,
      title: "Wanted: ACCT Textbook Bundle",
      titleZh: "求购：会计教材套装",
      category: "Textbooks",
      categoryZh: "教材资料",
      budget: 150,
      buyer: "Luna He",
      buyerZh: "Luna He",
      location: "Teaching A Lobby",
      locationZh: "TA 教学楼大堂",
      badge: "Wanted",
      badgeZh: "求购中",
      description:
        "Looking for a clean accounting textbook bundle for next semester. Notes are a plus, and pickup can be arranged on campus.",
      descriptionZh: "想收下学期用的会计教材套装，书况干净即可，有笔记更好，可在校内当面交接。",
      tags: ["ACCT", "Next Semester", "Bundle"],
      tagsZh: ["ACCT", "下学期", "套装"],
    },
    {
      id: 1002,
      title: "Wanted: Small Dorm Fridge",
      titleZh: "求购：小型宿舍冰箱",
      category: "Lifestyle Essentials",
      categoryZh: "生活用品",
      budget: 300,
      buyer: "Mason Liu",
      buyerZh: "Mason Liu",
      location: "Dorm 7 Lobby",
      locationZh: "七号宿舍大堂",
      badge: "Urgent Need",
      badgeZh: "急收",
      description:
        "Need a compact fridge in working condition before move-in week. Budget is flexible if delivery to dorm is convenient.",
      descriptionZh: "开学入住前想收一个能正常使用的小冰箱，如果能方便送到宿舍，预算可以再谈。",
      tags: ["Appliance", "Move-in", "Urgent"],
      tagsZh: ["电器", "入住", "急收"],
    },
  ],
};
